# Generated by Django 6.0.3 on 2026-03-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_birthday_profile_github_profile_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studies',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
