# Generated by Django 6.0.3 on 2026-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_github_alter_profile_gmail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resumen_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
