# Generated by Django 6.0.3 on 2026-03-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile_resumen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resumen_image',
            field=models.FileField(default='document/default.pdf', upload_to='document/'),
        ),
    ]
