# Generated by Django 6.0.3 on 2026-03-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_profile_resumen_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='resumen_image',
            new_name='resumen_pdf',
        ),
    ]
