# Generated by Django 6.0.3 on 2026-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_resumen_image_profile_resumen_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resumen_pdf',
            field=models.FileField(default='static/document/default.pdf', upload_to='static/document/'),
        ),
    ]
