# Generated by Django 6.0.3 on 2026-03-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_profile_resumen_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resumen_pdf',
            field=models.FileField(default='documents/default.pdf', upload_to='documents/'),
        ),
    ]
