# Generated by Django 6.0.3 on 2026-03-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_profile_resumen_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='resumen_pdf',
            new_name='resume_pdf',
        ),
    ]
