# Generated by Django 6.0.3 on 2026-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_resumen_pdf_profile_resume_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('emoji', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='about_long',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_long1',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_long2',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_short',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='traits',
            field=models.ManyToManyField(related_name='profiles', to='portfolio.trait'),
        ),
        migrations.AddField(
            model_name='profile',
            name='values',
            field=models.ManyToManyField(related_name='profiles', to='portfolio.value'),
        ),
    ]
