# Generated by Django 6.0.3 on 2026-04-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_education_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('live_url', models.CharField(blank=True, max_length=100)),
                ('github_url', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.projectcategory')),
                ('tag', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.projecttag')),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.projecttechstack')),
            ],
        ),
    ]
