# Generated by Django 6.0.3 on 2026-04-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_projectcategory_projecttag_projecttechstack_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-id']},
        ),
    ]
