# Generated by Django 6.0.3 on 2026-04-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttechstack',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
