# Generated by Django 6.0.3 on 2026-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_journey_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='journey_milestone',
            options={'ordering': ['year', 'id']},
        ),
        migrations.AlterField(
            model_name='journey_milestone',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
