# Generated by Django 6.0.3 on 2026-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_interest_alter_journey_milestone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('reading', models.CharField(max_length=100)),
                ('reading_sub', models.TextField()),
            ],
        ),
    ]
